name = "worker-sites-template"
main = "src/index.js"
compatibility_date = "2022-05-06"

site = { bucket = "./public" }

kv_namespaces = [
  { binding = "TODOS", id = "5846537e30474869823fc5eb204e8028", preview_id = "5846537e30474869823fc5eb204e8028" }
]
