# [env.jekyll]
name = "worker-site-jekyll"
type = "webpack"
route = ""
zone_id = ""
account_id = ""
[[kv-namespaces]]
binding = "STATIC_CONTENT"
id = "c417513a199c4289a1a0c8385c58a0e7"
bucket = "../jekyll-site/_site"

# # [env.gatsby]
# name = "worker-site-gatsby"
# type = "webpack"
# route = ""
# zone_id = ""
# account_id = ""
# [[kv-namespaces]]
# binding = "STATIC_CONTENT"
# id = "1f44a56679a040f0bb01ba39599ba704"
# bucket = "../gatsby-site/public"

# # [env.hugo]
# name = "worker-site-hugo"
# type = "webpack"
# route = ""
# zone_id = ""
# account_id = ""
# [[kv-namespaces]]
# binding = "STATIC_CONTENT"
# id = "9d28bd2bbb2c4e489006d7d8afa61f07"
# bucket = "../hugo-site/public"
