# [env.jekyll]
name = "worker-site-jekyll"
type = "webpack"
route = ""
zone_id = ""
account_id = ""
[[kv-namespaces]]
binding = "STATIC_CONTENT"
# why share namespace tag but not account/zone tags? 
# the tags should probably just all be blank
id = "c417513a199c4289a1a0c8385c58a0e7"
bucket = "../jekyll-site/_site"
# this folder nor `../` actually exist and is confusing
# for templates we try to make as generic as possible
# why not just make this `./public` or `./files` or some name ? 

# for environment template should be explained in a seperate env template
# # [env.gatsby]
# name = "worker-site-gatsby"
# type = "webpack"
# route = ""
# zone_id = ""
# account_id = ""
# [[kv-namespaces]]
# binding = "STATIC_CONTENT"
# id = "1f44a56679a040f0bb01ba39599ba704"
# bucket = "../gatsby-site/public"

# # [env.hugo]
# name = "worker-site-hugo"
# type = "webpack"
# route = ""
# zone_id = ""
# account_id = ""
# [[kv-namespaces]]
# binding = "STATIC_CONTENT"
# id = "9d28bd2bbb2c4e489006d7d8afa61f07"
# bucket = "../hugo-site/public"
